name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint
        run: flake8 --ignore=E501

      - name: Test
        run: pytest -q --disable-warnings

      - name: Build Docker image
        run: docker build -t cpi-recon .

      - name: Authenticate Docker to Artifact Registry
        run: |
          echo SKIP: gcloud auth configure-docker
